name: CI
on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "auto-deps"
      - "auto-deps*"
  pull_request:
    types: [synchronize]
  workflow_dispatch:
jobs:
  pre-check:
    # This job only runs for pull request comments
    name: Pre-check Script
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: |
            var run_ci = true;
            var against_branch = "devel";

            var pr = context.payload.pull_request;
            // console.log("PR", pr != null, pr != undefined);
            // console.log("PR Body", pr.body != null, pr.body != undefined);
            if (pr) {
              let pr_body = pr.body;
              console.log("PR Body", pr_body);
              if(pr_body) {
                const regexp = /!(\w+)(=\w+)?/g;
                const tag_matches = [...pr_body.matchAll(regexp)];
                for (const match of tag_matches) {
                  console.log(`Found tag: ${match[1]} = ${match[2]}`);
                  if (match[1] == "noci") {
                    run_ci = false;
                    break;
                  } else if (match[1] == "against") {
                    against_branch = match[2];
                  }
                }
              }
            }
            // console.log(context);
            let ret = {
              run_ci: run_ci,
              against_branch: against_branch
            };
            console.log("Returning", ret);
            return ret;
  build1:
    needs: pre-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script
        run: |
          echo "Running actions"