name: CI
on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "auto-deps"
      - "auto-deps*"
  pull_request:
  workflow_dispatch:
jobs:
  pre-check:
    # This job only runs for pull request comments
    name: Test PR trigger
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: |
            var pr = context.pull_request;
            console.log("Pull request", pr);
            if(pr != null) {
              console.log("Pull request number: " + pr.number);
              const result = await github.request(pr.issue_url);
              console.log("Issue data", result)
            }
            console.log(context);
  build1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script
        run: |
          echo "Running actions"