name: CI
on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "auto-deps"
      - "auto-deps*"
  pull_request:
  workflow_dispatch:
jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)
  build1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script
        run: |
          echo "Running actions"