name: CI
on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "auto-deps"
      - "auto-deps*"
  pull_request:
    types: [synchronize]
  workflow_dispatch:
jobs:
  pre-check:
    # This job only runs for pull request comments
    name: Pre-check
    runs-on: ubuntu-latest
    outputs:
      against: ${{ steps.pre-check.outputs.against }}
    steps:
      - id: pre-check
        uses: actions/github-script@v6
        with:
          script: |
            function parseTags(text) {
              const regexp = /!(\w+)(=[^\s]+)?/g;
              const tagMatches = [...text.matchAll(regexp)];
              return tagMatches;
            }

            var againstBranch = "devel";

            var pr = context.payload.pull_request;
            if (pr && pr.body) {
              const tagMatches = parseTags(pr.body);
              for (const match of tagMatches) {
                let key = match[1];
                let value = match[2] ? match[2].slice(1) : null;
                console.log(`Found tag: ${key} = ${value}`);
                if (key == "noci") {
                  core.setFailed("CI is disabled for this PR");
                  break;
                } else if (key == "against") {
                  if(value)
                    againstBranch = value;
                }
              }
            }

            core.setOutput("against", againstBranch);
  build1:
    needs: pre-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script
        run: |
          echo "Building against branch ${{needs.pre-check.outputs.against}}"