name: CI
on:
  pull_request:
    types: [edited]
jobs:
  pr-edit-check:
    # This job only runs for pull request comments
    name: PR edited
    runs-on: ubuntu-latest
    steps:
      - name: Script
        uses: actions/github-script@v6
        with:
          script: |
            var run_ci = true;
            var against_branch = "devel";

            var pr = context.payload.pull_request;
            // console.log("PR", pr != null, pr != undefined);
            // console.log("PR Body", pr.body != null, pr.body != undefined);
            if (pr) {
              let pr_body = pr.body;
              console.log("PR Body", pr_body);
              if(pr_body) {
                const regexp = /!(\w+)(=\w+)?/g;
                const tag_matches = [...pr_body.matchAll(regexp)];
                for (const match of tag_matches) {
                  console.log(`Found tag: ${match[1]} = ${match[2]}`);
                  if (match[1] == "noci") {
                    run_ci = false;
                    break;
                  } else if (match[1] == "against") {
                    against_branch = match[2];
                  }
                }
              }
            }
            console.log(context);